### ISSUE TITLE
Curious about the project

### ISSUE THREAD

**Issue by Neob91** [LoadLineCalibration/DXEditPlus#2]
Hello @LoadLineCalibration!

This project sounds amazing and I would love to play with it when it's released. I'm curious - are you doing everything from scratch, or are you reusing parts of the original UnrealEd 2.x? If so, I'm sure people would love to know the specifics, and I think it's worth including that info in the README.

By the way, I love the voiceover work you did for Project 2027 - I couldn't bring myself to play the mod without any voices, but now it's a completely different story. It's great to see the Deus Ex modding scene alive and well. Keep up the good work!

**Comment by LoadLineCalibration** [comment]
Hi!

I'm mainly building the program from scratch while using publicly available information (SDKs) on how it works. As for the interface, I'm almost entirely copying it from UnrealEd2, but I'd like to add some useful features. I did something similar with ConEditPlus — the program was developed from scratch, and the interface was copied from the original ConEdit, but I expanded and improved it.

Thanks, I'm glad you like the voiceover :)
